Descriptor objects
Shellborn/shellborn pull request #11
Opened 2023-11-22 09:51 UTC by JonasPfeifer05

Added basic structs and funcionallities to build up an ER-model

2023-11-22 12:12 UTC, ToBinio requested changes
some comments.

think a lot is a bit overcomplicated and should be shifted to the parser

2023-11-22 12:12 UTC, ToBinio commented on shellborn/src/relation/connection.rs
> +    pub fn zero_to_one<S: Into<String>>(to_name: S) -> Self {
same as above having these functions shifts the job of parsing the connection from them self to the builder

2023-11-22 12:48 UTC, JonasPfeifer05 commented on shellborn/src/attribute/mod.rs
> +pub enum Attribute {
yea seems resonable

2023-11-22 12:49 UTC, JonasPfeifer05 commented on shellborn/src/relation/builder.rs
> +    pub fn add_zero_to_one<S: Into<String>>(mut self, to_name: S) -> Self {
It makes sense to add a type for custom values like 3 or so, yes
but same here as above

2023-11-22 12:50 UTC, JonasPfeifer05 commented on shellborn/src/relation/cardinality.rs
> +    Zero,
It makes sense to add a type for custom values like 3 or so, yes
but same here as above

2023-11-22 12:50 UTC, JonasPfeifer05 commented on shellborn/src/relation/connection.rs
> +    pub fn zero_to_one<S: Into<String>>(to_name: S) -> Self {
same as above

2023-11-22 13:07 UTC, ToBinio commented on shellborn/src/relation/cardinality.rs
> +    Zero,
but doesn't that make parsing harder

2023-11-23 08:58 UTC, JonasPfeifer05 commented on shellborn/src/entity/builder.rs
> +    pub fn add_basic<S: Into<String>>(mut self, name: S) -> Self {
removed! new generic function add_attribute

2023-11-23 08:58 UTC, JonasPfeifer05 commented on shellborn/src/relation/builder.rs
> +    pub fn add_zero_to_one<S: Into<String>>(mut self, to_name: S) -> Self {
removed! new generic function add_connection

2023-11-23 09:00 UTC, JonasPfeifer05 commented on shellborn/src/relation/cardinality.rs
> +    Zero,
removed enums, changed to only use custom cardinalities

2023-11-23 09:01 UTC, JonasPfeifer05 commented on shellborn/src/relation/connection.rs
> +    pub fn zero_to_one<S: Into<String>>(to_name: S) -> Self {
removed enums, changed to only use custom cardinalities

2023-11-23 09:17 UTC, ToBinio approved these changes

2023-11-23 09:17 UTC, merged